version: "3"
services: 
    nginx:
        build: 
            context: project/docker/dev/nginx
        volumes:
            - ./project:/app
        ports: 
            - "8080:80"
        depends_on: 
            - php-fpm

    php-fpm:
        build: 
            context: project/docker/dev/php-fpm
        volumes: 
            - ./project:/app
        depends_on:
            - storage
            - db
            - redis

    php-cli:
        build:
            context: project/docker/dev/php-cli
        volumes:
            - ./project:/app
            - composer:/root/.composer/cache
        depends_on:
            - storage
            - db
            - redis
        tty: true

    storage:
        build:
            context: project/docker/dev/nginx
        volumes:
            - ./storage:/app
        ports:
            - "8081:80"
        
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes: 
            - db:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: app 
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: secret
    
    redis:
        image: 'redis:alpine'
        ports:
            - "63791:6379"
        volumes:
            - redis:/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080
            
    rabbitmq:
        image: rabbitmq:3.6.14-management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASSWORD: guest
        ports:
            - 15671:15671
            - 15672:15672
            - 5671:5671
            - 5672:5672
volumes:
    redis:
    db:
    composer: